import React from 'react';
import {ScanLine,ArrowUpRight,RefreshCw} from 'lucide-react';
import {EvidenceImage} from './Highlights';

export default function AutoMonitor({analysis:a,issues,observations,onOpen,onRetry}){
 const automatic=issues.filter(i=>i.automation),pending=automatic.filter(i=>i.status==='needs_review');
 const running=['starting','running'].includes(a?.state);
 return <section className="auto-monitor panel" aria-label="Automatic issue monitoring"><div className="auto-monitor-heading"><div><span className="eyebrow">AUTOMATIC SITE CHECKS</span><h2>The system finds it. Your team decides the action.</h2><p>Object detection → segmentation → issue creation → review</p></div><span className={'badge '+(running?'assigned':'confirmed')}>{running?'Analyzing recordings':a?.state==='completed'?'Analysis complete':a?.state==='failed'?'Analysis needs attention':a?.modelsReady?'Monitoring ready':'Models unavailable'}</span></div><div className="auto-monitor-status"><ScanLine size={20}/><div><strong>{a?.rule||'Possible dark cable obstruction'}</strong><span>{running?a.current:`${a?.processed||0} / ${a?.total||0} sampled frames processed · ${pending.length} issues awaiting review`}</span></div>{running?<progress aria-label="Analysis progress" max={a.total||1} value={a.processed||0}/>:<button className="btn" onClick={onRetry}><RefreshCw size={14}/>Check recordings</button>}</div><p className="auto-scope">Checks run automatically when the server starts. Full-resolution frames every 15 seconds, plus indexed evidence frames. Model scores indicate detection strength; they are not hazard probabilities.</p>{a?.errors?.length>0&&<details className="auto-errors"><summary>{a.errors.length} frame processing error(s)</summary>{a.errors.map((e,i)=><p key={i}>{e}</p>)}</details>}{a?.state==='unavailable'&&<p className="auto-errors">{a.current}</p>}{automatic.length>0?<div className="auto-findings">{automatic.slice(-3).reverse().map(i=>{const o=observations.find(o=>o.id===i.observationId);return <article key={i.id}><EvidenceImage observation={o}/><div className="auto-finding-heading"><span className="badge needs_review">{i.status==='needs_review'?'Needs review':i.status.replace('_',' ')}</span><small>Detection score {i.automation.score.toFixed(2)}</small></div><h3>{i.title}</h3><p>{i.id} · Clip {o.videoId.slice(1)} at {Math.floor(o.timestamp/60)}:{String(o.timestamp%60).padStart(2,'0')}</p><button className="btn primary" onClick={()=>onOpen(i)}>Review {i.id}<ArrowUpRight size={14}/></button></article>})}</div>:<div className="auto-empty">{running?'Analyzing images. Any qualifying finding will arrive here with its highlight and issue already created.':'No automatic findings yet. Frames without a qualifying detection do not create an issue.'}</div>}</section>
}
